---
- name: Install required packages
  loop:
    - lvm2
  package:
    name: "{{ item }}"
    state: present
  tags:
    - lvm

- name: Create volume group
  loop: "{{ lvm_group_volumes + lvm_host_volumes }}"
  loop_control:
    label: "{{ item.group }}: {{ item.disks | join(',') }}"
  lvg:
    vg: "{{ item.group }}"
    pvs: "{{ item.disks | join(',') }}"
    pesize: "4"
  tags:
    - lvm

- name: Resize physical volume
  loop: "{{ lvm_group_volumes + lvm_host_volumes }}"
  loop_control:
    label: "{{ item.group }}: {{ item.disks | join(',') }}"
  changed_when: False
  command: "pvresize {{ item.disks | join(' ') }}"
  tags:
    - lvm

- name: Create logical volume
  loop: "{{ lvm_group_volumes + lvm_host_volumes }}"
  loop_control:
    label: "{{ item.group }}: {{ item.name }}"
  lvol:
    vg: "{{ item.group }}"
    lv: "{{ item.name }}"
    size: "{{ item.size }}"
    resizefs: "{{ item.resizefs | default(True) }}"
    state: "{{ item.state | default('present') }}"
  tags:
    - lvm

- name: Create volume filesystem
  loop: "{{ lvm_group_volumes + lvm_host_volumes }}"
  loop_control:
    label: "{{ item.group }}: {{ item.name }}"
  filesystem:
    fstype: "{{ item.fstype | default('ext4') }}"
    dev: "/dev/mapper/{{ item.group }}-{{ item.name | replace('-', '--') }}"
  tags:
    - lvm

- name: Mount volume filesystem
  loop: "{{ lvm_group_volumes + lvm_host_volumes }}"
  loop_control:
    label: "{{ item.group }}: {{ item.name }}"
  mount:
    path: "{{ item.mountpoint }}"
    src: "/dev/mapper/{{ item.group }}-{{ item.name | replace('-', '--') }}"
    fstype: "{{ item.fstype | default('ext4') }}"
    opts: "{{ item.mountopts | default([]) | join(',') or omit }}"
    state: "{{ 'mounted' if item.state | default('present') == 'present' else 'absent' }}"
  tags:
    - lvm

...
